# Generated by Django 5.2.1 on 2025-05-10 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RemindMeLater",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remind_at_time", models.DateTimeField()),
                ("message", models.TextField(max_length=500)),
                (
                    "send_method",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("Email", "Email")],
                        default="Email",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
