# Generated by Django 5.2.1 on 2025-05-10 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remindmelater",
            name="created_at",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2025, 5, 10, 14, 17, 48, 605829, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
