# Generated by Django 5.2.1 on 2025-05-10 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_remindmelater_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remindmelater",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 10, 14, 20, 21, 990490, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
