# Generated by Django 5.2.1 on 2025-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_remindmelater_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remindmelater",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
