# Generated by Django 5.2.1 on 2025-05-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_remindmelater_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remindmelater",
            name="created_at",
        ),
    ]
