# Generated by Django 5.2.1 on 2025-05-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_remindmelater_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remindmelater",
            old_name="send_method",
            new_name="reminder_send_method",
        ),
    ]
