# Generated by Django 5.2.1 on 2025-05-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_rename_send_method_remindmelater_reminder_send_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remindmelater",
            name="reminder_send_method",
        ),
    ]
